#if canImport(SwiftUI)
  import Foundation
  import SwiftUI
  import TraktionUI

  @main
  @MainActor
  struct TRAKTIONApp: App {
    @State private var model = NativeWorkspaceModel()

    var body: some Scene {
      WindowGroup {
        TraktionWorkspaceView(model: model)
          #if DEBUG
            .task { importUITestFixtureIfRequested() }
          #endif
      }
    }

    #if DEBUG
      @State private var didLoadUITestFixture = false

      private func importUITestFixtureIfRequested() {
        guard !didLoadUITestFixture else { return }
        didLoadUITestFixture = true
        // Test input is generated by FixtureForge and copied into this app's
        // simulator data container. This invokes the production import path;
        // neither order confirmation nor reconstruction is bypassed.
        let scenarios = ["baseline": 3, "duplicate-capture": 4, "missing-middle": 2]
        guard let scenario = ProcessInfo.processInfo.environment["TRAKTION_UI_FIXTURE"],
          let count = scenarios[scenario],
          let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
            .first
        else { return }
        let directory = documents.appendingPathComponent("UIFixtures", isDirectory: true)
          .appendingPathComponent(scenario, isDirectory: true)
        let urls = (1...count).map { number in
          directory.appendingPathComponent(String(format: "capture-%03d.png", number))
        }
        model.importCaptures(from: urls)
      }
    #endif
  }
#else
  import Foundation

  @main
  enum TRAKTIONApp {
    static func main() {
      print("The TRAKTION native shell requires macOS or iOS.")
    }
  }
#endif
